# Generated by Django 5.2.7 on 2025-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('necklace', 'Necklace'), ('earring', 'Earring'), ('bangle', 'Bangle'), ('bracelet', 'Bracelet')], default='necklace', max_length=20),
        ),
    ]
